services:
  - type: static
    name: mavrix-cafe
    env: static
    buildCommand: cd frontend && npm install
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: mavrix-cafe-api
    env: node
    buildCommand: cd backend && rm -f yarn.lock && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard 